// swift-tools-version:5.9
// Generated by build-ios.sh — do not edit by hand.

import PackageDescription

let package = Package(
    name: "CSPICE",
    platforms: [
        .iOS(.v13),
        .tvOS(.v15),
        .macOS(.v10_15)
    ],
    products: [
        .library(
            name: "CSPICE",
            targets: ["CSPICE"]
        )
    ],
    targets: [
        .binaryTarget(
            name: "CSPICE",
            url: "https://github.com/mkrasnorutsky/CSPICE/releases/download/1.0.11/CSPICE.xcframework.zip",
            checksum: "5356467f9b7d7861577091320547a3c90a90d995b075960266f857b516eacc88"
        )
    ]
)
